name: 'caresync'
version: '1.0.0'
config-version: 2

profile: 'caresync'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  caresync:
    staging:
      +materialized: view
      +database: "{{ env_var('SNOWFLAKE_DATABASE_STAGING', 'NEXORA_STAGING_WH') }}"
      +schema: staging
    marts:
      +materialized: table
      +database: "{{ env_var('SNOWFLAKE_DATABASE_PROD', 'NEXORA_PROD_WH') }}"
      +schema: prod
